### ISSUE TITLE
Zijn dit buttons, of links naar andere pagina's?

### ISSUE THREAD

**Issue by krijnhoetmer** [CelinexPutte/the-web-is-for-everyone-interactive-functionality#4]
Via `<a href="/book?id=....">` kun je bijvoorbeeld een vooraf ingevulde zone aangeven.

https://github.com/CelinexPutte/the-web-is-for-everyone-interactive-functionality/blob/a6abfb19ba414cd7be50d88eec7e829049f136f9/views/partials/zones.ejs#L24-L25

**Comment by CelinexPutte** [comment]
Buttons in tegels naar linkjes veranderd

**Comment by CelinexPutte** [comment]
Gelukt!
